"""Leave-one-attack-family-out configs for CTU-13.

    python -m nidra.scripts.make_lofo_configs --families neris rbot --out-dir config/lofo

The primary CTU-13 split already withholds two families entirely (Virut and
NSIS.ay are in the holdout, Murlo appears only in test), so the families it
cannot say anything about are the two it TRAINS on: Neris and Rbot. A
leave-one-family-out config moves every capture of one family to the
evaluation side and trains on the rest.

This deliberately breaks chronology — training on 2011-08-19 to predict
2011-08-12 — which is why it is a secondary experiment and not the primary
protocol. What it answers is narrower and worth having: given that the model
never saw this family, can it forecast it?

Validation is the two chronologically last non-held-out captures, fixed by
rule rather than chosen by result. Captures shorter than L+K = 36 windows
(scenarios 5, 7, 11) are excluded everywhere.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from nidra.utils.config import load_config

USABLE = ["ctu_1", "ctu_2", "ctu_3", "ctu_4", "ctu_6", "ctu_8", "ctu_9", "ctu_10", "ctu_12", "ctu_13"]
#: chronological order of the usable captures, by capture start
CHRONOLOGICAL = ["ctu_1", "ctu_2", "ctu_3", "ctu_4", "ctu_13", "ctu_6", "ctu_8", "ctu_9", "ctu_10", "ctu_12"]


def lofo_split(days: dict, family: str) -> dict:
    held = [k for k in USABLE if days[k].get("family") == family]
    if not held:
        raise ValueError(f"no usable capture has family {family!r}")
    rest = [k for k in CHRONOLOGICAL if k not in held]
    if len(rest) < 3:
        raise ValueError(f"holding out {family!r} leaves {len(rest)} captures — not enough to train and validate")
    val = rest[-2:]
    train = [k for k in rest if k not in val]
    return {"train_days": train, "val_days": val, "test_days": held, "holdout_days": []}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-config", default="config/ctu13.yaml")
    parser.add_argument("--families", nargs="+", default=["neris", "rbot"])
    parser.add_argument("--out-dir", default="config/lofo")
    args = parser.parse_args()

    base = load_config(args.base_config)
    days = base["dataset"]["days"]
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for family in args.families:
        split = lofo_split(days, family)
        body = {
            "extends": str(Path("..") / Path(args.base_config).name),
            "splits": {**split, "_note": f"leave-one-family-out: {family} withheld from training. "
                                         f"Chronology is deliberately broken; see the module docstring."},
        }
        path = out_dir / f"without_{family}.yaml"
        path.write_text(
            f"# Leave-one-family-out: {family} is never trained on.\n"
            f"# Generated by nidra.scripts.make_lofo_configs — do not hand-edit.\n"
            + yaml.safe_dump(body, sort_keys=False)
        )
        n_test = len(split["test_days"])
        print(f"{path}: train={split['train_days']} val={split['val_days']} test={split['test_days']} ({n_test} captures)")


if __name__ == "__main__":
    main()
